#!url=https://raw.githubusercontent.com/Simonerrror/ShadowRocket/main/modules/anti_advertising.module
#!icon=https://raw.githubusercontent.com/Simonerrror/ShadowRocket/main/modules/icons/anti_advertising.png
#!name=90 · Anti-Advertising
#!desc=Блокировщик рекламы и трекеров через единый rule-set список репозитория (REJECT).

[Rule]

# Wildberries search and other app actions use this endpoint.
DOMAIN-SUFFIX,antibot.wildberries.ru,DIRECT

RULE-SET, https://raw.githubusercontent.com/Simonerrror/ShadowRocket/main/rules/anti_advertising.01.list,REJECT
RULE-SET, https://raw.githubusercontent.com/Simonerrror/ShadowRocket/main/rules/anti_advertising.02.list,REJECT
RULE-SET, https://raw.githubusercontent.com/Simonerrror/ShadowRocket/main/rules/anti_advertising.03.list,REJECT
