#!name=Anti-Advertising Custom (REJECT)
#!desc=Блокировщик рекламы и трекеров через единый rule-set список репозитория (REJECT) с локальными исключениями.
[Rule]
# === NVIDIA WHITELIST ===
DOMAIN-SUFFIX,telemetry.gfe.nvidia.com,DIRECT
DOMAIN-SUFFIX,prod.otel.kaizen.nvidia.com,DIRECT
DOMAIN-KEYWORD,nvidia,DIRECT

# === SYSTEM SNITCHES (STEALTH) ===
DOMAIN,optimizationguide-pa.googleapis.com,DIRECT
DOMAIN,signaler-pa.clients6.google.com,DIRECT
DOMAIN-SUFFIX,gvt2.com,DIRECT
DOMAIN-SUFFIX,events.data.microsoft.com,DIRECT

RULE-SET, https://raw.githubusercontent.com/Simonerrror/ShadowRocket/main/rules/anti_advertising.list,REJECT
