#!url=https://raw.githubusercontent.com/Simonerrror/ShadowRocket/main/modules/GFN-AM.module
#!name=20_01 · GFN Direct
#!desc=Правила GFN/AM для прямого доступа (DIRECT).

[General]
always-real-ip = *.nvidiagrid.net,*.geforcenow.com,*.nvidia.com

[Rule]
# 1. Стриминговые серверы (IP-CIDR)
IP-CIDR,37.186.111.0/24,DIRECT,no-resolve
IP-CIDR,17.253.150.10/32,DIRECT

DOMAIN,optimizationguide-pa.googleapis.com,DIRECT
DOMAIN,signaler-pa.clients6.google.com,DIRECT
DOMAIN-SUFFIX,events.data.microsoft.com,DIRECT
DOMAIN-SUFFIX,browser-intake-datadoghq.com,DIRECT

DOMAIN-KEYWORD,geforce,DIRECT
DOMAIN-KEYWORD,geforcenow,DIRECT
DOMAIN-KEYWORD,nvidia,DIRECT
DOMAIN-SUFFIX,nvidiagrid.net,DIRECT
