#!/usr/bin/env python3
"""Embed the generated HAPP deeplinks into the potato-link Worker."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = REPO_ROOT / "HAPP/DEFAULT.DEEPLINK"
RU_INPUT = REPO_ROOT / "HAPP/RU-VPN.DEEPLINK"
DEFAULT_OUTPUT = REPO_ROOT / "cloudflare/potato-link/dist/destinations.js"
DEEPLINK_PREFIX = "happ://routing/onadd/"
MAX_DEEPLINK_LENGTH = 16 * 1024
BASE64_RE = re.compile(r"[A-Za-z0-9+/]+={0,2}")


def validate_deeplink(raw: str, path: Path) -> str:
    lines = raw.splitlines()
    if len(lines) != 1 or not lines[0]:
        raise ValueError(f"{path}: deeplink must be a single line")
    value = lines[0]
    if len(value) > MAX_DEEPLINK_LENGTH:
        raise ValueError(f"{path}: deeplink exceeds 16 KiB")
    if not value.startswith(DEEPLINK_PREFIX):
        raise ValueError(f"{path}: unexpected deeplink prefix")
    payload = value.removeprefix(DEEPLINK_PREFIX)
    if BASE64_RE.fullmatch(payload) is None:
        raise ValueError(f"{path}: invalid base64 payload")
    return value


def read_deeplink(path: Path) -> str:
    return validate_deeplink(path.read_text(encoding="utf-8"), path)


def build_module(default: str, ru: str) -> str:
    return (
        "// Generated by scripts/build_potato_link_worker.py; do not edit.\n"
        "export const DESTINATIONS = Object.freeze({\n"
        f"  default: {json.dumps(default)},\n"
        f"  ru: {json.dumps(ru)},\n"
        "});\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--default-input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--ru-input", type=Path, default=RU_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    output = build_module(
        read_deeplink(args.default_input),
        read_deeplink(args.ru_input),
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
